export const mockSessions = [
  {
    id: 1,
    date: "2025-09-14",
    module: "confidenceCoach",
    confidenceDelta: +2,
    isVoiceQuiz: false,
  },
  {
    id: 2,
    date: "2025-09-14",
    module: "inQuizzo",
    confidenceDelta: +1,
    isVoiceQuiz: true,
  },
  {
    id: 3,
    date: "2025-09-13",
    module: "microLearning",
    confidenceDelta: +1,
    isVoiceQuiz: false,
  },
  {
    id: 4,
    date: "2025-09-13",
    module: "confidenceCoach",
    confidenceDelta: +2,
    isVoiceQuiz: false,
  },
  {
    id: 5,
    date: "2025-09-12",
    module: "socialMentor",
    confidenceDelta: +1,
    isVoiceQuiz: false,
  },
  {
    id: 6,
    date: "2025-09-11",
    module: "confidenceCoach",
    confidenceDelta: +2,
    isVoiceQuiz: false,
  },
  {
    id: 7,
    date: "2025-09-10",
    module: "inQuizzo",
    confidenceDelta: +1,
    isVoiceQuiz: true,
  },
  {
    id: 8,
    date: "2025-09-09",
    module: "confidenceCoach",
    confidenceDelta: +2,
    isVoiceQuiz: false,
  },
  {
    id: 9,
    date: "2025-09-08",
    module: "microLearning",
    confidenceDelta: +1,
    isVoiceQuiz: false,
  },
];
